// {
//   "customerCode":"كود العميل",
//   "phoneNumber":"رقم الهاتف",
//   "password":"كلمه المرور",
//   "login":"تسجيل الدخول",
//   "forgetYourPassword":"كلمه المرور؟ نسيت",
//   "send":"ارسال",
//   "backToLogin":"العوده اىل تسجيل الدخول",
//   "otpCode":"رمز التحقق المؤقت",
//   "verify":"تحقق",
//   "resendTheCode":"اعاده ارسال رمز التحقق",
//   "newPassword":"كلمه المرور الجديده",
//   "password(Again)":"اعاده ادخال كلمه المرور",
//   "changePassword":"تغيير كلمه المرور",
//   "welcome":"مرحبا",
//   "totalBalance":"اجمالى الرصيد",
//   "profile":"الملف الشخصى",
//   "purchaseOrders":"اوامر الشراء",
//   "shipments":"الشحنات",
//   "coupons":"الكوبونات",
//   "home":"الرئيسيه",
//   "drivers":"السائقين",
//   "invoices":"الفواتير",
//   "deposits":"االيداعات",
//   "uploadPayment":"اضافه ايداع",
//   "notification":"الإشعارات ",
//   "addNewPurchaseOrder":"اضافه اوامر الشراء",
//   "ExFactory":"أرض مصنع",
//   "canceled":"كميه ملغاه",
//   "netTotal":"الصافى",
//   "shipTo":"جهه الشحن",
//   "select":"اختار",
//   "deliveryType":"طريقة التوصيل",
//   "delivery":"وصال",
//   "packingType":"نوع التعبئه",
//   "bulk":"سائب",
//   "bagged":"معبأ",
//   "cementType":"نوع المنتج",
//   "quantity":"الكمية",
//   "requiredQuantity":"الكميه المطلوبه",
//   "orderDetails":"تفاصيل امر الشراء",
//   "item":"المنتج",
//   "amount":"سعرالمنتج",
//   "freight":"نولون",
//   "total":"اجمالى",
//   "confirm":"تأكيد",
//   "back":"العودة",
//   "confirmAndAddNew":"تأكيد و اضافه أمر شراء جديد",
//   "addShipments":"اضافه شحنه",
//   "theDataBelowAreForTheLast30Days":"البيانات المتاحه لأخر30 يوم",
//   "waitingArrival":"إنتظار وصول",
//   "arrivedShipments":"قيد التسجيل",
//   "issuedShipments":"انتظار التحميل",
//   "underPacking":"تحت التحميل",
//   "dispatched":"تم الشحن",
//   "canceled":"ملغاه",
//   "backToShipments":"العوده الى قائمه الشحنات",
//   "shipmentsFrom":"الشحنات من تاريخ",
//   "reset":"اعاده ضبط",
//   "backToList":"العوده",
//   "shipmentId":"رقم الشحنه",
//   "date-Time":"التاريخ- الوقت",
//   "driverName":"اسم السائق",
//   "purchaseOrderId":"رقم امر الشراء",
//   "cancel":"الغاء",
//   "edit":"تعديل",
//   "share":"أرسال",
//   "cancelShipmentOnly":"الغاء الشحنه فقط",
//   "cancelShipmentsAndCoupons":"الغاء الشحنه+كوبوناتها",
//   "selectADriver":"اختيار سائق",
//   "addNewDriver":"إضافة سائق",
//   "freeCoupons":"رصيد الكوبونات المتاحه",
//   "linkedToShipments":"كوبونات معلقه",
//   "issued":"فى انتظار تحميل",
//   "underPacking":"تحت التحميل",
//   "addDriver":"إضافة سائق",
//   "delegationExpiry":"انتهاء التفويض",
//   "delegationStart":"بدايه التفويض",
//   "idNumber":"الرقم القومى",
//   "edit":"تعديل",
//   "driverName":"اسم السائق",
//   "uploadDriverIdImage":"تحميل صوره الرقم القومى",
//   "uploadPayment":"اضافة ايداع",
//   "choose":"اختر",
//   "add":"اضافة",
//   "notifications":"اشعارات",
//   "orderCreation":"تم قطع امر بيع",
//   "setting":"اعدادات",
//   "changeLanguage":"تغيير اللغة",
//   "changePassword":"تغيير كلمة المرور",
//    "logout":"خروج",
//    "change":"تغيير",
//    "changeTheLanguage":"تغيير اللغة"
//
// }
