import 'app_pathes.dart';

class AppImages{

 static String userLoginCircle = "${iconsPath}User-circle-login-icon.svg";
 static String mushamLogo = "${iconsPath}musham-logo.svg";
 static String groupViewIcon = "${iconsPath}group-view-icon.svg";
 static String listViewIcon = "${iconsPath}list-view-icon.svg";
 static String homeIcon = "${iconsPath}home-icon.svg";
 static String stockIcon = "${iconsPath}tdaol-icon.svg";
 static String meetingsIcon = "${iconsPath}meetings-icon.svg";
 static String comitteesIcon = "${iconsPath}people-.svg";
 static String comitteesIcon2 = "${iconsPath}people_icon.svg";
 static String moreIcon = "${iconsPath}more-icon.svg";
 static String userIcon = "${iconsPath}User_icon.svg";
 static String signatureIcon = "${iconsPath}signature_icon.svg";
 static String arrowIcon = "${iconsPath}arrow.svg";
 static String suggestionIcon = "${iconsPath}suggestion_icon.svg";
 static String chatIcon = "${iconsPath}Chat_icon.svg";
 static String languageIcon = "${iconsPath}language_icon.svg";
 static String signOutIcon = "${iconsPath}Sign_icon.svg";
 static String notificationIcon = "${iconsPath}notification-icon.svg";
 static String arrowDownIcon = "${iconsPath}arrow-down-icon.svg";
 static String backButtonIcon = "${iconsPath}backbutton_icon.svg";
 static String filterIcon = "${iconsPath}filter_icon.svg";
 static String callIcon = "${iconsPath}call-icon.svg";
 static String mailIcon = "${iconsPath}mail-icon.svg";
 static String locationIcon = "${iconsPath}location-icon.svg";
 static String stockCountIcon = "${iconsPath}stock-count.svg";
 static String membersCountIcon = "${iconsPath}members-count.svg";
 static String downloadReport = "${iconsPath}download-icon.svg";
 static String emptyImage = "${imagesPath}EmptyState.svg";
 static String errorImage = "${imagesPath}error-image.svg";
 static String folderIcon = "${iconsPath}Folder-open-icon.svg";
 static String pdfFileIcon = "${iconsPath}pdf-file-icon.svg";
 static String textFileIcon = "${iconsPath}text-file-icon.svg";
 static String wordFileIcon = "${iconsPath}word-file-icon.svg";
 static String smallBackButtonIcon = "${iconsPath}small-back-icon.svg";
 static String linkedDeviceIcon = "${iconsPath}linked-devices-icon.svg";
 static String doneImage = "${imagesPath}Done-state.svg";
 static String rectangleSignature = "${imagesPath}Rectangle 5014.svg";
 static String infoIconStock = "${iconsPath}info-icon-stock.svg";
 static String uploadSignature = "${imagesPath}Upload_light.svg";
 static String commercialNoIcon = "${iconsPath}commericalNo-icon.svg";
 static String nominalStockValueIcon = "${iconsPath}NominalStockValue-icon.svg";
 static String sharesCount = "${iconsPath}shares-count-icon.svg";
 static String logoutIcon = "${iconsPath}logout-icon.svg";
 static String deleteItem = "${iconsPath}delete-item.svg";
 static String notificationBell = "${imagesPath}Bell_notification.svg";
 static String internetConnectionImage = "${imagesPath}internet-connection-image.svg";
 static String calendarIcon = "${iconsPath}Date-range-light-icon.svg";
 static String activeCommittee= "${iconsPath}active-committee.svg";
 static String notActiveCommittee = "${iconsPath}notactiveIconCommittee.svg";
 static String buildingIcon = "${iconsPath}building-icon.svg";
 static String companyIcon = "${iconsPath}companyIcon.svg";
 static String userIconApplicationDetails = "${iconsPath}User-icon.svg";
 static String zoomMeetingIcon = "${iconsPath}zoom_icon.svg";
 static String mapsMeetingIcon = "${iconsPath}maps_icon.svg";
 static String infoMeetingIcon = "${iconsPath}info_icon.svg";
 static String calendarMeetingsIcon="${iconsPath}calendar_icon.svg";
 static String clockMeetingsIcon="${iconsPath}clock_icon.svg";
 static String votingIcon="${iconsPath}Bell_light .svg";
 static String engBackButtonIcon="${iconsPath}engBackButton_icon.svg";
 static String notificationButtonIcon="${iconsPath}notification.svg";
 static String notificationArrowIcon="${iconsPath}arrow_notification.svg";
 static String chatSendIcon="${iconsPath}chat-send-icon.svg";
 static String translationIcon="${iconsPath}translation_icon.svg";
 static String checkedBoxIcon="${iconsPath}checked_box_icon.svg";
 static String boxIcon="${iconsPath}box_icon.svg";


}